### ISSUE TITLE
Can only see top of brown quake background screen in right eye

### ISSUE THREAD

**Issue by carn1x** [SuperV1234/quakevr#10] opened 2020-03-07 13:38 UTC
After loading `quakespasm-sdl2-release` the game appears to load, I can hear the game, left trigger shoots the shotgun. However I can't see the game world at all, and only the top of the quake brown background image in the right eye, with blackness above it, and the left eye is totally black.

I'm on Oculus Rift CV1, on a Radeon 5700XT, with latest 20.2.2 drivers.

<img width="674" alt="qvr3" src="https://user-images.githubusercontent.com/783281/76144445-7b591880-6078-11ea-9af0-6e621867ed62.PNG">
<img width="805" alt="qvr1" src="https://user-images.githubusercontent.com/783281/76144446-7c8a4580-6078-11ea-903d-a2f531e9850d.PNG">
Oculus mirror, only shows this in the right eye, left eye is black. Interestingly if I move my head around, this brown background does slightly move a few pixels around as if some sort of easing vs momentum, almost like it it rendering in "VR space" somehow.
<img width="955" alt="qvr2" src="https://user-images.githubusercontent.com/783281/76144447-7c8a4580-6078-11ea-996c-22520e37e674.PNG">
 
Installation and run steps followed were exactly:

1. Install Quake 1 from Steam
2. Install VC++ 64bit 
3. Install HD music/textures
4. Install mod
5. Run `quakespasm-sdl2-release`

**Comment by carn1x** [comment] 2020-03-07 15:51
Seems that after running the game in Non-VR and then running the VR binary again fixed this.

**Comment by SuperV1234** [comment] 2020-03-08 01:15
That is very weird. Going to close this as a one-off, but please open again if it re-occurs.

**Closed by SuperV1234** 2020-03-08 01:15 UTC

**Comment by carn1x** [comment] 2020-03-10 20:43
@SuperV1234 got this bug again today after installing 0.0.3. Solved by the same method of starting the Non-VR build and quitting. Perhaps something in the README might help?

**Comment by SuperV1234** [comment] 2020-04-24 21:58
The cause of this bug is likely the default value of the `vr_msaa` CVar. Possibly the same issue as #23

**Comment by SuperV1234** [comment] 2020-04-26 15:59
This is fixed in the upcoming v0.0.4. As a workaround, set the `vr_msaa` cvar in config.cfg to 0 or 1.
