### ISSUE TITLE
45 degree rotation issuses, add 30 degree rotation

### ISSUE THREAD

**Issue by alexisneverlate** [SuperV1234/quakevr#9] opened 2020-03-04 00:23 UTC
When rotating 45 degrees in approx 1/2 cases (using oculus rift cv1+controllers) it doesnt rotate or rotates back immediately after rotation, or it "stacks" rotation commands and then rotates 90-270 degrees.

Also 30 rotation could be good

Also - see rotation in other games (Gorn, Boneworks etc) for reference.

Many thanks for your work!

**Comment by SuperV1234** [comment] 2020-03-04 22:20
I've changed the menu in the next patch so that you can choose any increment of 5° degrees for your snap turn settings. I cannot reproduce the stacked rotations, though. Are you using v0.0.2?

**Comment by SuperV1234** [comment] 2020-03-07 16:30
Fixed in #11

**Closed by SuperV1234** 2020-03-07 16:30 UTC
