### ISSUE TITLE
"Framebuffer incomplete" error 

### ISSUE THREAD

**Issue by BleepBloop32** [SuperV1234/quakevr#23] opened 2020-03-21 01:46 UTC
I get this message in the cmd and my game does not display properly, I can see the menu card way down by my nose and cannot get into gameplay.

I have a Ryzen 5 3600, RX 5700, and using the HTC Vive.

**Comment by carn1x** [comment] 2020-03-21 08:05
Duplicate of #10 ?

**Comment by BleepBloop32** [comment] 2020-03-21 19:52
I tried running the game not in VR at first like you did but I still got the error

**Comment by carn1x** [comment] 2020-04-26 13:32
My fix for this was to edit the `id1/config.cfg` file provided by the mod and change `msaa` value to something less than 9.

**Comment by SuperV1234** [comment] 2020-04-26 15:58
Closing as duplicate of #10. This is fixed in the upcoming v0.0.4. As a workaround, set the `vr_msaa` cvar in `config.cfg` to `0` or `1`.

**Closed by SuperV1234** 2020-04-26 15:58 UTC
